spring:
  application:
    name: lafabrica
  security:
    loginPage: /login
    form:
      login:
        defaultSuccessUrl: http://localhost:4200
logging:
  level:
    org:
      springframework:
        security: info